spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homeloandb
    username: root
    password: abc123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: homeloanService
  mail:    host: smtp.gmail.com
    username: homeloan124578@gmail.com
    password: homeloan123
    properties:      mail:
        smtp:
          auth: true
          socketFactory: 
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
server:
  port: 9001
  servlet:
    context-path: /api/homeloan

