spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homeloandb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: HomeLoanService
server:
  port: 9000
  servlet:
    context-path: /api/homeloan
